spring:
  datasource:
    url: jdbc:sqlserver://miservidordemo.database.windows.net:1433;database=miBaseDeDatosDeEjemplo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: usuarioazure
    password: Password123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port:9191



